### PR TITLE
JWT and Marketplace Works

### PR DESCRIPTION
**Pull request by jm2693**
Added file that gets the current idToken for the user's session that will be used to verify authorization for sensitive API calls.
Import { getAuthHeaders } from '../utils/getJwt';
     Use that header in any of your requests accordingly i.e.
          const verifiedHeader = await getAuthHeaders();
          
You may use the getAuthHeaders() method and replace that in your API call or call getJwt() directly:
const verifiedHeader = await getAuthHeaders();
    try {
      const response = await fetch('endpoint', {
        method: 'VERB',
        headers: verifiedHeader,
        
MarketPlace can now post listings using this. 
Please verify these work.

### CODE REVIEW

**Review by lukasdchang — APPROVED** [review]
This is amazing

**Review by lukas-arteni-rutgers — APPROVED** [review]
fire

**Review by lukas-arteni-rutgers — APPROVED** [review]
approving this approval

**Review by lukas-arteni-rutgers — APPROVED** [review]
i get it now

**Pull request merged**
