### PR TITLE
Makes You SignUp/Login for Posting

### PR DESCRIPTION
**Pull request by jm2693**

### CODE REVIEW

**Review by dal279 — COMMENTED** [review]
still needs work

**Review by dal279 — DISMISSED** [review]
needs work :///

**Review by lukasdchang — DISMISSED** [review]
works great

**Review by dal279 — APPROVED** [review]
looks good

**Review by lukasdchang — COMMENTED** [review]
The home page is the settings page and I don't have to sign in to make a listing

**Review by lukasdchang — CHANGES_REQUESTED** [review]
Fix before merging ^

**Review by lukasdchang — APPROVED** [review]
_now_ it works

**Pull request merged**
